site_name: Dokumentation MGDM BAFU
site_url: https://nrohrbach.github.io/MGDM-Dokus/
theme:
  name: material
  palette:
    scheme: slate # Dunkler Modus (optional)
    primary: indigo

nav:
  - Home: index.md
  - Dokumentation: Flachmoore/Modelldokumentation.md  # Hier deine .md Datei eintragen
